Write-Host "DiscountHub real provider next steps" -ForegroundColor Cyan
Write-Host ""
Write-Host "1. List available provider targets:"
Write-Host "   .\scripts\provider_catalog_list.ps1"
Write-Host ""
Write-Host "2. Open docs for a provider, for example eBay:"
Write-Host "   .\scripts\provider_open_docs.ps1 -Id ebay_partner_network"
Write-Host ""
Write-Host "3. Apply to the affiliate network / developer program."
Write-Host ""
Write-Host "4. When approved, add the real feed/API URL to config:"
Write-Host "   .\scripts\provider_add_to_config.ps1 -Id real_provider -Name 'Real Provider' -Url 'https://real-url' -Adapter generic_products"
Write-Host ""
Write-Host "5. Test and sync:"
Write-Host "   .\scripts\provider_test_url.ps1 -FeedUrl 'https://real-url'"
Write-Host "   .\scripts\provider_sync_from_config.ps1"
